-- Supprimer tous les enregistrements de la table Materiel
DELETE FROM materiel;
-- Ajout d'entitées pour la classe Materiel
INSERT INTO materiel (id,title,quantity,description,url) VALUES (1,'canon eos 60D',1,'Appareil photo APS-C Canon','https://zupimages.net/up/22/24/akfn.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (2,'Sac photo',1,'Le sac est trés important pour pouvoir emporter son matériel en toute sécurité','https://zupimages.net/up/22/24/bt1f.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (3,'Objectif Canon 10-22mm F/3.5-4.5',1,'Objectif grand angle, utilisé surtout pour les photos de paysage','https://zupimages.net/up/22/24/k4uw.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (4,'Objectif Canon 15-85mm F/3.5-5.6',1,'Objectif polyvalent','https://zupimages.net/up/22/24/aev2.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (5,'Objectif Canon 70-300 F/4-5.6',1,'Tele-objectif trés utile pour la photo d animaux, puissant et leger','https://zupimages.net/up/22/24/m1k0.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (6,'Objectif Sigma 35mm F/1.4',1,'Objectif pour la photo de portrait, mais bien que ce soit une focale fixe, il est trés lumineux et permet donc des prises de vues en basse lumiére','https://zupimages.net/up/22/24/g5gg.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (7,'Objectif Sigma 150-600 F/5-6.3',1,'Gros télé-objectif, il est puissant mais lourd, c est pourquoi je ne l utilise que sur trépied','https://zupimages.net/up/22/24/tb0o.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (8,'Appreil photo étanche',1,'Un petit appareil secondaire pour les photos sous la pluie ou sous l eau sans craintes','https://zupimages.net/up/22/24/yptb.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (9,'Jumelles',1,'L outil indispensable du photographe amateur, la paire de jumelles','https://zupimages.net/up/22/24/f3m6.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (10,'Grip de batterie',1,'Gadget bien utile lorsque l on utilise l appreil sur trepied. Il evite les changements de batterie et dispose des mêmes boutons en mode vertical','https://zupimages.net/up/22/24/h6ha.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (11,'Flash annulaire',1,'Flash annulaire qui se fixe sur l objectif et qui permet d avoir un éclairage à 360 degrés. Bien utile en photo macro','https://zupimages.net/up/22/24/ah6d.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (12,'Batteries',4,'Batterie Canon et sous marque. Attention elle sont sensibles au froid','https://zupimages.net/up/22/24/y8cm.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (13,'Filtre polarisant',1,'Filtre polarisant, il permet de saturer les verts de la végétation et le bleu du ciel. Il permet également d éviter les reflets.','https://zupimages.net/up/22/24/c9y1.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (14,'Filtre neutre',1,'Filtre dont le seul but est de protéger la lentille frontale de l objectif.','https://zupimages.net/up/22/24/491a.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (15,'Filtre gris neutre',5,'Filtres qui permettent de diminuer la quantité de lumiére qui rentre dans l objectif, afin d augmenter le temps de pose pour obtenir des filets par exemple','https://zupimages.net/up/22/24/qst6.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (16,'Télécommande',1,'Télécommande ou intervalométre, elle permet de prérégler un nombre de prises de vues en un temps choisit. Elle permet egalement de déclencher sans faire vibrer l appareil','https://zupimages.net/up/22/24/lo64.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (17,'Flash',1,'Flash pour un maximum de lumiére','https://zupimages.net/up/22/24/ka40.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (18,'Trépied pliable',1,'Petit trépied pliable, il est moins stable que le gros trépied, mais il permet de mettre l appreil jusqu au raz du sol','https://zupimages.net/up/22/24/s0i2.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (19,'Lens pen',1,'Lens pen, ou stylo à lentille. Il permet un nettoyage tout en douceur des objectifs, avec à un bout une brosse de poils souple, et à l autre bout un tampon de feutre','https://zupimages.net/up/22/24/ccls.jpg');
INSERT INTO materiel (id,title,quantity,description,url) VALUES (20,'Piége photo',1,'Piége photo, il prend des photos de jour comme de nuit en detectant les mouvements. Il peut également enregistrer des videos. Sa batterie de 8 piles lui assurre une bonne autonomie','https://zupimages.net/up/22/24/sp7m.jpg');
-- Supprimer tous les enregistrements de la table Photo
DELETE FROM photo;
-- Ajout d'entitées pour la classe Photo
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES (1,'Brocards',5.0,'https://zupimages.net/up/22/22/phcv.jpg',80,300.0,2613,6400,45.481105,-0.662779,'eos60D',1.0,'https://zupimages.net/up/22/22/5nkq.png',3920,'J''ai pris cette photo le 10 décembre 2016 alors que le soleil n''etait pas encore levé, d''ou la mise en iso maximum 6400, ce qui ajoute énormément de bruit sur l''image, que j''ai tanté de récuperer avec une mise en noir et blanc (désaturation).');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(2,'Buse',4.75,'https://zupimages.net/up/22/22/k055.jpg',1600,225.0,1564,100,45.441142,-0.699178,'eos60D',1.0,'https://zupimages.net/up/22/22/b54o.png',2346,'J''ai pris cette photo le 10 Aout 2017, il s''agit d''une buse variable cherchant des ascendances thermiques pour rester en l''air le plus longtemps possible. J''aime surtout les différentes couleurs de ses plumes, et l''aisance de son vol.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(3,'Cerf',5.0,'https://zupimages.net/up/22/12/rec4.jpg',50,300.0,2745,6400,45.748144,-1.185744,'eos60D',1.0,'https://zupimages.net/up/22/22/x4bp.png',4117,'J''ai pris cette photo le 10 decembre 2016, il s''agit du tout premier cerf que j''ai vu en vrai, il chercait à manger dans un champ alors que le soleil n''était pas encore levé. Et malgré ma position pour éviter qu''il ne me voit');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(4,'Cigognes',5.0,'https://zupimages.net/up/22/22/51fs.jpg',8000,300.0,2047,3200,45.748384,-1.080961,'eos60D',1.0,'https://zupimages.net/up/22/22/wdlm.png',3071,'Dans la région il y a enormément de cigognes, mais les voir voler toutes ensemble est un spectacle magnifique. ');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(5,'Cygne',5.0,'https://zupimages.net/up/22/12/892a.jpg',2000,300.0,2483,1250,45.828667,-1.012778,'eos60D',1.0,'https://zupimages.net/up/22/22/sk3m.png',3725,'Pour photographier ce Cygne j''ai du attendre 2 heures sous mon filet de camouflage qu''il veuille bien se secouer les ailes. J''aime bien la transparence des ailes car le soleil était plutôt bas. Dommage que le reflet dans l''eau ne soit pas complet.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(6,'Lapin',5.0,'https://zupimages.net/up/22/12/zlth.jpg',1000,300.0,3456,1000,45.83808,-0.955855,'eos60D',1.0,'https://zupimages.net/up/22/22/3v2d.png',5184,'Le lapin qui m''a surprit juste avant que ce ne soit lui qui soit surpris, l''instant à durait le temps du déclenchement! Pas le temps de faire la mise au point.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(7,'Ragondin',5.0,'https://zupimages.net/up/22/22/704z.jpg',8,300.0,1485,100,45.837668,-0.963785,'eos60D',1.0,'https://zupimages.net/up/22/22/w1ku.png',5227,'Le ragondin, trés bon nageur. Mais qui résiste mal au froid dans nos régions car il n'' est pas originaire d''ici mais d''Amerique du sud, il fut ramené pour l''élevage à cause de sa fourrure.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(8,'Renard',5.0,'https://zupimages.net/up/22/22/ya13.jpg',25,300.0,3456,1000,45.481659,-0.645594,'eos60D',1.0,'https://zupimages.net/up/22/22/ng89.png',5184,'La nature est toujours imprévisible, et je ne m''attendais pas à rencontrer ce renard, lorsque je suis parti récuperer mon piége photo en foret. On s''aperçoit, on se fixe, puis chacun repars de son coté. C''est vraiment un animal magnifique.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(9,'Sanglier',2.0,'https://zupimages.net/up/22/22/d0j3.jpg',30,3.0,3456,2675,45.476089,-0.665,'piége photo',1.0,'https://zupimages.net/up/22/22/m01a.png',4608,'En me baladant en foret je découvre ce point d''eau. Autour duquel quelques traces de pas qui m''indique de récents passages. Je décide donc d''y installer mon piége photo. Dés le lendemain, mon piége a pris des photos d''un sanglier.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(10,'Spatules',5.0,'https://zupimages.net/up/22/22/q32c.jpg',1000,300.0,2003,640,45.848524,-0.971656,'eos60D',1.0,'https://zupimages.net/up/22/22/sj3a.png',3004,'Animal peu connu et pourtant bien présent dans notre département, la spatule blanche. Elle est facilement reconnaissable à son bec en forme de spatule. Mais son vol est moins bruyant que celui du cygne.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(11,'Buse',4.5,'https://zupimages.net/up/22/24/zlcd.jpg',800,140.0,1394,100,45.44086702821327,-0.6845986960175265,'eos60D',1.0,'https://zupimages.net/up/22/24/jtge.png',2091,'Buse variable avant de se poser sur une branche. Le dessous de ses ailes est toujours trés beau en vol.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(12,'Chevreuil',5.0,'https://zupimages.net/up/22/24/c6hq.jpg',100,300.0,2543,1600,45.81193844506269,-0.9114901280589915,'eos60D',1.0,'https://zupimages.net/up/22/24/15r7.png',3815,'Parfois on attend des heures pour ne rien voir et parfois on rencontre un animal au bord de la route en pleine journée, c''est ce qu''il s''est passé avec ce chevreuil. J''ai du me garer un peu plus loin.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(13,'Cygne',5.0,'https://zupimages.net/up/22/24/k97m.jpg',2000,300.0,2730,1600,45.844722231362596,-0.9635935962560227,'eos60D',1.0,'https://zupimages.net/up/22/24/t3s3.png',4095,'Il est rare que je fasse des photos aussi peu réalistes, mais pour une fois je voulais montrer cette impression de blancheur immaculée du cygne comparé au paysage.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(14,'Cygnes',5.0,'https://zupimages.net/up/22/24/htd8.jpg',400,300.0,2293,400,45.74425742942804,-1.0670667548048995,'eos60D',1.0,'https://zupimages.net/up/22/24/ykn5.png',3439,'Deux cygnes pour un passage bas et bruyants. Inséparables, toujours par deux.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(15,'Cygnes',5.0,'https://zupimages.net/up/22/24/k4qv.jpg',3200,548.0,816,800,45.920926081306554,-0.9740995052774637,'eos60D',1.0,'https://zupimages.net/up/22/24/qjma.png',1212,'Une des rares photos ou je savais à l''avance ce que je vouais obtenir et ou j''ai du attendre que cela se produise. Les deux Cygnes face à face qui forment un coeur.');
INSERT INTO photo (id,animal,aperture,big_url,denom_expo,focale,height,iso,latitude,longitude,model_device,num_expo,small_url,width,description) VALUES	(16,'Verdier',5.0,'https://zupimages.net/up/22/24/21sf.jpg',1000,260.0,1879,1600,45.84035961599488,-0.9348654612267082,'eos60D',1.0,'https://zupimages.net/up/22/24/l6cg.png',2818,'Ce petit verdier est tellement rapide que même le mode rafale de mon Canon eos60D à eu du mal à suivre (5,3 photos/secondes; max 16 photos).');
-- Supprimer tous les enregistrements de la table Video
DELETE FROM video;
-- Ajout d'entitées pour la classe Video
INSERT INTO video (id,title,description,url,latitude,longitude) VALUES (1,'Station de lagunage','C etait une trés belle sortie photo d oiseaux.','RygyEnGHxQ4',45.919820,-0.973912);
INSERT INTO video (id,title,description,url,latitude,longitude) VALUES (2,'Piége photo','Sortie pour poser un piége photo à coté d une souille ou les sangliers viennent la nuit','yinkVRc8d-I',45.47202,-0.661748);